# [Info] 基本信息
site_name: book # 左上角标题
site_url: https://xuxu0927.github.io/book/
site_author: Xuxu0927
site_description: 通信learn


# [UI] 界面设置
## [top]
theme:
  name: material
  custom_dir: docs/mkdocs/overrides
  font: 
    text: Roboto
  palette: 
    - scheme: default # 默认日间模式
      primary: yellow # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - content.code.copy # 代码复制
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer # 上一个下一个按钮
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章,文档可以直接附加到区域
  # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share # 将搜索结果分享
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github-alt
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/Xuxu0927/book # 右上角点击跳转的链接
repo_name: book # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2024 gis-xh # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/Xuxu0927
      name: GitHub | Xuxu0927 # 鼠标悬浮提示


# [Extensions] 扩展
plugins:
  - open-in-new-tab:
  - search:
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - zh
        - en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags: # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  - git-revision-date-localized: # 日期显示
      # ["date","datetime","iso_date","iso_datetime","timeago","custom"]
      type: timeago
      enable_creation_date: true # 创建时间
      timezone: Asia/Shanghai
  - git-authors: # 显示作者
  - glightbox: # 图像缩放
  - meta-manager: # 元数据管理


markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list: # 给图片后面添加{width="300"}设置大小
  - md_in_html: 
  - tables: 
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      linenums: false # 显示行号
      linenums_style: table
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences: # 代码块高亮插件
  - pymdownx.inlinehilite: # 段落中内置的小代码高亮
  - admonition: # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details: # admonition需要
  - pymdownx.caret: # markdown上标显示
  - pymdownx.tilde: # markdown下标显示
  - pymdownx.mark: # markdown突出显示


extra_javascript:
  # latex支持
  - mkdocs/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - mkdocs/css/unordered-list-symbols.css # 多个无序列表符号
  - mkdocs/css/img-center.css # 图像居中


  # [Navigtion] 导航栏
nav:
  - heihei: 
    - index.md
  - 量子物理:
    - 0.Preface 序: 上帝掷骰子吗/0.Preface 序.md
    - 1.Golden Age 黄金时代: 上帝掷骰子吗/1.Golden Age 黄金时代.md
    - 2.Dark Clouds 乌云: 上帝掷骰子吗/2.Dark Clouds 乌云.md
    - 3.Falling Fireball 火流星: 上帝掷骰子吗/3.Falling Fireball 火流星.md
    - 4.Into the Mist 白云深处: 上帝掷骰子吗/4.Into the Mist 白云深处.md
    - 5.The Dawn  曙光: 上帝掷骰子吗/5.The Dawn  曙光.md
    - 6.Two Sides of One Coin  殊途同归: 上帝掷骰子吗/6.Two Sides of One Coin  殊途同归.md
    - 7.Uncertainty Principle  不确定性: 上帝掷骰子吗/7.Uncertainty Principle  不确定性.md
    - 8.The Duel  决战: 上帝掷骰子吗/8.The Duel  决战.md
    - 9.At the Crossroads  歧途: 上帝掷骰子吗/9.At the Crossroads  歧途.md
    - 10.Back to Eden  回归经典: 上帝掷骰子吗/10.Back to Eden  回归经典.md
    - 11.Judgement of the Inequality  不等式的判决: 上帝掷骰子吗/11.Judgement of the Inequality  不等式的判决.md
    - 12.New Adventures  新探险: 上帝掷骰子吗/12.New Adventures  新探险.md
    - 13.Finale  尾声: 上帝掷骰子吗/13.Finale  尾声.md
  - 健身:
    - 入门: 健身/健身.md
